@baseUrl = http://127.0.0.1:5000/api

### 1 get word
GET {{baseUrl}}/getword

### 2 insert word
POST {{baseUrl}}/insert
Content-Type: application/json

{
  "meaning": "horse",
  "hiragana": "うま",
  "katakana": "ウマ"
}

### 3 try success
PATCH {{baseUrl}}/attempt
Content-Type: application/json

{
  "wid": "1",
  "success": "True",
  "fail": "False"
}

### 4 try failure
PATCH  {{baseUrl}}/attempt
Content-Type:  application/json

{
    "wid": "1",
    "success": "False",
    "fail": "True"
}

### 5 update kana attempt
PATCH  {{baseUrl}}/update
Content-Type: : application/json

{
    "hiragana": "だいがく",
    "katakana": "ダイカグ"
}